services:
  db:
    image: mongo:6.0
    restart: always
    networks:
      - lams-net
    volumes:
      - lams-db:/data/db

  api:
    image: lams-api:v1.0.0
    depends_on:
      - db
    restart: always
    networks:
      - lams-net
   
    environment:
      - LAMS_PORT=8080 
      - LAMS_DB_URI=mongodb://db:27017/LaMsDB
      - LAMS_SESSION_SECRET=1234567890
    volumes:
      - lams-uploads:/app/public/uploads
  
  client:
    image: lams-client:v1.0.0
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080
      - APP_PORT=80
    networks:
      - lams-net
    ports:
      - "3000:80"
    

networks:
  lams-net:
    name: lams-net
    driver: bridge

volumes:
  lams-db:
  lams-uploads: