version: '3.8'

services:
  db:
    image: mongo:${MONGODB_VERSION}
    restart: always
    networks:
      - lams-net
    volumes:
      - db-data:/data/db
      - db-cfg:/data/configdb

  backend:
    image: ${DOCKER_IMAGE_TAG}
    depends_on:
      - db
    restart: always
    networks:
      - lams-net
    ports:
      - 127.0.0.1:8090:8080
    environment:
      LAMS_PORT: 8080

      LAMS_DB_URI:
      LAMS_SESSION_SECRET:
    volumes:
      - upload-data:/app/public/uploads

networks:
  lams-net:
    name: lams-net
    driver: bridge

volumes:
  db-data:
  db-cfg:
  upload-data: