# Use the official Node.js 18 slim image
FROM node:18-slim

# Install PM2 globally as a process manager
RUN npm install -g pm2

# Drop privileges to the non-root user
USER node

# Set NPM global dependency path
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --omit=dev

# Copy the application source code
COPY . .

# Assume production environment
ENV NODE_ENV=production

# Volume for file uploads
VOLUME [ "/app/public/uploads" ]

# Expose the application port
EXPOSE 3001

# Use PM2 to start the application and watch for crashes
ENTRYPOINT ["pm2-runtime", "start", "npm", "--", "start"]
